#Application ID
app.grayjay.Grayjay
app.zen_browser.zen
com.bitwarden.desktop
com.github.Matoking.protontricks
com.github.marhkb.Pods
com.github.tchx84.Flatseal
com.github.vladimiry.ElectronMail
com.obsproject.Studio
com.protonvpn.www
com.ranfdev.DistroShelf
com.rtosta.zapzap
com.usebottles.bottles
com.vysp3r.ProtonPlus
dev.vencord.Vesktop
dev.zed.Zed
eu.betterbird.Betterbird
in.cinny.Cinny
io.ente.auth
io.github.flattool.Ignition
io.github.flattool.Warehouse
io.github.ilya_zlobintsev.LACT
io.github.prateekmedia.appimagepool
io.github.ungoogled_software.ungoogled_chromium
io.missioncenter.MissionCenter
it.mijorus.gearlever
net.ankiweb.Anki
org.fedoraproject.MediaWriter
org.feichtmeier.Musicpod
org.fkoehler.KTailctl
org.freedesktop.LinuxAudio.Plugins.TAP
org.freedesktop.LinuxAudio.Plugins.swh
org.freedesktop.Platform
org.freedesktop.Platform
org.freedesktop.Platform.Compat.i386
org.freedesktop.Platform.GL.default
org.freedesktop.Platform.GL.default
org.freedesktop.Platform.GL.default
org.freedesktop.Platform.GL.default
org.freedesktop.Platform.GL.nvidia-580-82-07
org.freedesktop.Platform.GL32.default
org.freedesktop.Platform.GL32.default
org.freedesktop.Platform.GL32.nvidia-580-76-05
org.freedesktop.Platform.GL32.nvidia-580-82-07
org.freedesktop.Platform.VAAPI.Intel
org.freedesktop.Platform.VAAPI.Intel
org.freedesktop.Platform.VAAPI.nvidia
org.freedesktop.Platform.VulkanLayer.MangoHud
org.freedesktop.Platform.VulkanLayer.OBSVkCapture
org.freedesktop.Platform.VulkanLayer.vkBasalt
org.freedesktop.Platform.codecs-extra
org.freedesktop.Platform.ffmpeg-full
org.freedesktop.Platform.ffmpeg_full.i386
org.freedesktop.Platform.openh264
org.freedesktop.Sdk
org.freedesktop.Sdk.Extension.llvm18
org.freedesktop.Sdk.Extension.rust-stable
org.gimp.GIMP
org.gimp.GIMP.HEIC
org.gnome.Boxes
org.gnome.Boxes.Extension.OsinfoDb
org.gnome.Platform
org.gnome.Platform
org.gnome.Platform.Compat.i386
org.gtk.Gtk3theme.adw-gtk3
org.gtk.Gtk3theme.adw-gtk3-dark
org.kde.KStyle.Adwaita
org.kde.KStyle.Adwaita
org.kde.KStyle.Adwaita
org.kde.Platform
org.kde.Platform
org.kde.Platform
org.kde.filelight
org.kde.gwenview
org.kde.kcalc
org.kde.kdenlive
org.kde.okular
org.keepassxc.KeePassXC
org.onlyoffice.desktopeditors
org.telegram.desktop
org.winehq.Wine.gecko
org.winehq.Wine.mono
xyz.tytanium.DoorKnocker
